##  template for a Welcome message to be emailed to class (delete this line)
## Note that the From: address will be replaced by the email address of the account
## from which the message is sent.
From: teacher@somewhere.edu (Jan Teacher)
Subject: online homework for Math 123
Message:
    Hi $FN,

Our WeBWorK course is at:
https://somewhere.edu/webwork2/JT_123

Your username/password is:
$LOGIN/$SID

You should change your password once you have logged in by visiting
Account Settings in the sidebar navigation.

Have fun,
Jan

