From: gage@math.rochester.edu (MIKE GAGE) 
Reply-To: gage@math.rochester.edu
Subject: maa101 notice
Message: 
    Hi $FN,

Your course is at 

http://hosted.webwork.rochester.edu/webwork2/Floyd_math1111

Your login name is $LOGIN and your initial password is $LOGIN.

You should change your password, once you have logged in, by clicking on the password/email link in the upper left

Helpful urls are:  http://webwork.math.rochester.edu/ (click on the logo) and the discussion group there.

Also http://webwork.math.rochester.edu/docs/docs/courseadmin/usingwebwork.html

although that is not completely up to date.  Ask questions in the discussion group -- there is usually pretty quick response.

Have fun.

Take care,

Mike
