---
name: Check Formatting of Code Base

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore: [main, develop]
  pull_request:

jobs:
  perltidy:
    name: Check Perl file formatting with perltidy
    runs-on: ubuntu-24.04
    container:
      image: perl:5.38
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: cpanm -n Perl::Tidy@20260204
      - name: Run perltidy
        shell: bash
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          shopt -s extglob globstar nullglob

          perl_files=(./**/*.p[lm] ./**/*.t ./**/*.at)

          for f in bin/* bin/dev_scripts/*; do
              if [[ -f "$f" && ! "$f" == *.* ]]; then
                  if head -n 1 "$f" | grep -qE '^#!.*(\bperl\b)'; then
                      perl_files+=("$f")
                  fi
              fi
          done

          if [ ${#perl_files[@]} -gt 0 ]; then
              perltidy --pro=./.perltidyrc -b -bext='/' "${perl_files[@]}"
              git diff --exit-code
          fi

  prettier:
    name: Check JavaScript, style, and HTML file formatting with prettier
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install Dependencies
        run: cd htdocs && npm ci --ignore-scripts
      - name: Check formatting with prettier
        run: cd htdocs && npm run prettier-check
