---
name: Lint Code Base

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore: [main, develop]
  pull_request:

jobs:
  perlcritic:
    name: Lint Perl files with perlcritic
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libperl-critic-perl
      - name: Run perlcritic
        shell: bash
        run: perlcritic ./lib
